name: CI Web Components

on: pull_request

jobs:
  build_and_test_web_components:
    runs-on: ubuntu-latest
    name: Build & Test Web Components
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node Modules
        working-directory: ./packages/web-components
        run: npm install

      - name: Build Web Components
        working-directory: ./packages/web-components
        run: npm run build

      - name: Install Playwright Browsers
        working-directory: ./packages/web-components
        run: npx playwright install --with-deps

      - name: Test Web Components
        working-directory: ./packages/web-components
        run: npm run test